### ISSUE TITLE
Mount of type "Local" does not support active update notifications

### ISSUE THREAD

**Issue by Laupe** [icewind1991/files_inotify#1]
<del>
NC version 12

```
# sudo -u www-data php /home/apps/cloud/occ files_external:notify 5
Mount of type "Local" does not support active update notifications
```
</del>

# I'm taking back. I just do not have a php library. My fault. Sorry

**Comment by spfuetzner** [comment]
I have the exact same error message. What php library did you not have?

**Comment by schniepp** [comment]
I bet it was INotify. Try `pecl install INotify`
