### ISSUE TITLE
Notify is not supported with the used smb version

### ISSUE THREAD

**Issue by addaitrs** [icewind1991/files_inotify#6]
[Icewind\SMB\Exception\RevisionMismatchException]  
Notify is not supported with the used smb version

Although it appears I'm connecting with SMB 3.1.1 I still get this error.

**Comment by icewind1991** [comment]
This is the wrong repo, this is for the (local) inotify based `occ files_external:notify` not the smb one.

But to answer your question, unfortunately using smb notify is only supported using the SMB1 protocol due to a limitation in smbclient.
